#!/bin/bash

# MySQL 명령어 실행
mysql -h "$DB_ENDPOINT" -u "$DB_USERNAME" -p"$DB_PASSWORD" <<EOT
CREATE DATABASE IF NOT EXISTS userDB;
CREATE DATABASE IF NOT EXISTS gameDB;
CREATE DATABASE IF NOT EXISTS chatDB;

USE userDB;
CREATE TABLE IF NOT EXISTS userTBL ( 
    id VARCHAR(10) NOT NULL PRIMARY KEY,
    nickname VARCHAR(30) NOT NULL,
    password CHAR(60) NOT NULL,
    e_mail VARCHAR(320) NOT NULL UNIQUE, 
    phone_number VARCHAR(13) NOT NULL, 
    balance BIGINT DEFAULT 0,
    modified_date DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

USE gameDB;
CREATE TABLE IF NOT EXISTS gameinfoTBL ( 
    seq INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    id VARCHAR(10) NOT NULL,
    type ENUM('FOOTBALL', 'BASEBALL', 'BASKETBALL', 'ICEHOCKEY', 'HANDBALL') NOT NULL,
    matchid VARCHAR(8) NOT NULL,
    gameDate DATETIME NOT NULL,
    home VARCHAR(50) NOT NULL,
    away VARCHAR(50) NOT NULL,
    wdl ENUM('HOME', 'DRAW', 'AWAY')  NOT NULL,
    odds DECIMAL(5,2) NOT NULL,
    price BIGINT DEFAULT 0 NOT NULL, 
    status ENUM ('BEFORE', 'PLAYING', 'FINISHED') NOT NULL DEFAULT 'BEFORE',
    modified_date DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY (id, matchid)
);

CREATE TABLE IF NOT EXISTS gameresultTBL ( 
    seq INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    id VARCHAR(10) NOT NULL,
    type ENUM('FOOTBALL', 'BASEBALL', 'BASKETBALL', 'ICEHOCKEY', 'HANDBALL') NOT NULL, 
    matchid VARCHAR(8) NOT NULL,
    gameDate DATETIME NOT NULL,
    home VARCHAR(50) NOT NULL,
    away VARCHAR(50) NOT NULL,
    odds DECIMAL(5,2) NOT NULL,
    price BIGINT DEFAULT 0, 
    winner ENUM('HOME', 'DRAW', 'AWAY') NOT NULL,
    result ENUM('WIN', 'LOSE')  NOT NULL,
    resultPrice BIGINT DEFAULT 0,
    modified_date DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY (id, matchid),
    FOREIGN KEY (id, matchid) REFERENCES gameinfoTBL(id, matchid) ON DELETE CASCADE
);

USE chatDB;
CREATE TABLE IF NOT EXISTS roomTBL ( 
    roomid VARCHAR(8) PRIMARY KEY,
    modified_date DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS messageTBL (
    roomid VARCHAR(8) NOT NULL,
    id VARCHAR(10) NOT NULL,
    content TEXT NOT NULL,
    time DATETIME(6) NOT NULL,
    PRIMARY KEY (roomid, id, time),
    FOREIGN KEY (roomid) REFERENCES roomTBL(roomid) ON DELETE CASCADE
);
EOT